# -*- coding: utf-8 -*-
__author__ = 'guti'


'''
Configuration generated by default and override.
'''

import config_default
from transwarp.db import Dict


def merge(default, override):
    result = dict()
    for k, v in default.iteritems():
        if k in override:
            if isinstance(v, dict):
                result[k] = merge(v, override[k])
            else:
                result[k] = override[k]
        else:
            result[k] = v
    return result


def to_dict(d):
    result = Dict()
    for k, v in d.iteritems():
        result[k] = to_dict(v) if isinstance(v, dict) else v
    return result

configs = config_default.configs

try:
    import config_override
    configs = merge(configs, config_override.configs)
except ImportError:
    pass

configs = to_dict(configs)
